<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pt_team"
 *
 * Auto generated by Extension Builder 2018-02-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Team',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Markus',
    'author_email' => 'kontakt@programmier-tipps.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '7.6.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.9.99',
            'extbase' => '',
            'fluid' => '',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
